[project]
name = "py-img-query"
version = "0.1.0"
description = "Given a json file with image paths and attributes, allows to quickly visualize examples based on the selected attributes. "
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=4.3.0",
]
